package com.example.newsfinal
import android.support.v4.app.FragmentPagerAdapter
import android.content.Context;
import android.support.v4.app.Fragment
import android.support.v4.app.FragmentManager
import com.google.gson.Gson

class CategoriesAdapter(private val myContext: Context, fm: FragmentManager, internal var totalTabs: Int) : FragmentPagerAdapter(fm) {

    // this is for fragment tabs
    override fun getItem(position: Int): Fragment? {
        when (position) {
            0 -> {
                var gson = Gson()
                val newsString =  """[{"title": "Nous ne ferons pas marche arrière", "description": "Des centaines de milliers de manifestants dans les rues d’Alger Nous ne ferons pas marche arrière Marée humaine, hier, à Alger.La rue a mis dans son collimateur une nouvelle cible : le chef d’état-major et vice-ministre de la Défense, Ahmed Gaïd Salah. Pour la première fois depuis le 22 février dernier, les manifestants exigent son départ.","date": "22 Avril 2019", "image": "imgNews1", "categorie": "national"},
                    {"title": "Nous ne ferons pas marche arrière", "description": "Des centaines de milliers de manifestants dans les rues d’Alger Nous ne ferons pas marche arrière Marée humaine, hier, à Alger.La rue a mis dans son collimateur une nouvelle cible : le chef d’état-major et vice-ministre de la Défense, Ahmed Gaïd Salah. Pour la première fois depuis le 22 février dernier, les manifestants exigent son départ.","date": "22 Avril 2019", "image": "imgNews1", "categorie": "national"},
                    {"title": "Les étudiants ne lâchent pas prise", "description": "Alger, 14 mai 2019. 10h30. Sous un soleil printanier, le cortège composé de plusieurs dizaines d’étudiants de différentes universités s’ébranle depuis la Fac centrale en direction de la Grande-Poste.", "date": "15 Mai 2019 ", "image": "imgNews1","categorie": "national"},
                    {"title": "Crise vénézuélienne : Juan Guaido a-t-il perdu la partie ?", "description": "Depuis qu’il s’est déclaré président par intérim le 23 janvier, Juan Guaido n’a eu de cesse d’appeler les militaires à rompre les rangs et à tourner le dos au chef de l’Etat socialiste. Il comptait pour cela sur le soutien de dizaines de milliers de personnes, qui descendaient dans la rue à chacun de ses appels à manifester.Mais depuis le soulèvement manqué du 30 avril et l’offensive du pouvoir contre les «traîtres» à l’origine de la tentative de rébellion, le vent semble avoir tourné dans la rue. Samedi, ils n’étaient qu’entre 1500 et 2000 sur la place Alfredo Sadel, dans un quartier de l’est de Caracas majoritairement acquis à l’opposition.","date": "13 Mai 2019", "image": "imgNews1", "categorie": "international"},
                    {"title": "Yémen : Les Houthis se retirent des ports d’Al Hodeïda", "description": "Les rebelles houthis du Yémen ont remis le contrôle de la sécurité des ports d’Al Hodeïda, sur la mer Rouge, à la «garde côtière», mais du travail demeure pour éliminer tout signe de présence militaire, a annoncé hier l’ONU.Le président du Comité de coordination des redéploiements, le général danois Michael Lollesgaard, a salué le transfert de «la sécurité des ports à la garde côtière», selon un communiqué officiel. «Il reste encore beaucoup de travail à faire pour éliminer les signes (de présence militaire), mais la coopération a été très bonne», a-t-il jugé. Si le redéploiement est total, il pourrait donner une impulsion aux efforts de l’ONU pour mettre un terme à la guerre et à la catastrophe humanitaire au Yémen. A signaler que la gestion des revenus des trois ports en question devait être discutée hier à Amman avec leurs représentants et le gouvernement du Yémen, a annoncé lundi l’ONU.","date": "15 Mai 2019", "image": "imgNews1", "categorie": "international"},
                    {"title": "JSMB : Les joueurs réclament leur argent", "description": "Les joueurs de la JSM Béjaïa ont réitéré leurs revendications liées à la régularisation de leur situation financière, puisqu’ils ont interpellé la direction afin d’accélérer les démarches et tenir ses promesses pour le versement de leurs salaires qui tarde à se matérialiser depuis la fin","date": "15 Mai 2019", "image": "imgNews1", "categorie": "Sport"},
                    {"title": "JS Kabylie : Réception en l’honneur des jeunes catégories", "description": "Lundi dans la soirée, l’hôtel Ittourar de Tizi Ouzou a abrité une réception en l’honneur des jeunes catégories de la JS Kabylie et leurs staffs techniques.Les U13 et U12, champions de wilaya de l’année 2018/2019 dans leurs catégories respectives, étaient les premiers à être  reçus et félicités pour leur bon parcours, et ce,  dans une ambiance bon enfant, marquée par la présence de la direction du club kabyle et de nombreux invités. Le président de la JSK, Cherif Mellal, a pris la parole pour féliciter les champions et les vainqueurs du play-off.","date": "22 Avril 2019", "image": "imgNews1", "categorie": "Sport"},
                    {"title": "Ligue 1 : CRB – JSS en nocturne", "description": "La Ligue de football professionnel (LFP) a communiqué sur son site officiel les horaires des rencontres de la 28e journée. Encore une fois, la LFP n’arrive pas à programmer tous les matches à la même heure pour éviter toutes les spéculations sur le résultat final des rencontres.", "date": "15 Mai 2019 ", "image": "imgNews1","categorie": "national"},
                    {"title": "Mouloudia d’Alger : Casoni débarque à Alger", "description": "L’entraîneur du Mouloudia pour la nouvelle saison, le Français Bernard Casoni, et comme annoncé dans ces mêmes colonnes, est depuis hier à Alger où il séjournera durant quatre jours.Bernard Casoni, dont la mission à la tête du club algérois ne débutera officiellement qu’au mois de juin prochain, puisque l’équipe est toujours sous la coupe de Mohamed Mekhazeni pour ce qui reste de la saison en cours, aura néanmoins à régler certains détails inhérents à son récent engagement avec le MCA, avec notamment la paperasse nécessaire pour l’établissement de son permis de travail, mais surtout arrêter avec exactitude le programme de préparation d’intersaison, qui débutera à la mi-juin.","date": "15 Mai 2019", "image": "imgNews1", "categorie": "Sport"}
                   ]"""
                val list: List<News> = gson.fromJson(newsString , Array<News>::class.java).toList()
                return ListNews.newInstance(list)
            }
            1 -> {
                var gson = Gson()
                val newsString =  """[{"title": "Nous ne ferons pas marche arrière", "description": "Des centaines de milliers de manifestants dans les rues d’Alger Nous ne ferons pas marche arrière Marée humaine, hier, à Alger.La rue a mis dans son collimateur une nouvelle cible : le chef d’état-major et vice-ministre de la Défense, Ahmed Gaïd Salah. Pour la première fois depuis le 22 février dernier, les manifestants exigent son départ.","date": "22 Avril 2019", "image": "imgNews1", "categorie": "national"},
                    {"title": "Nous ne ferons pas marche arrière", "description": "Des centaines de milliers de manifestants dans les rues d’Alger Nous ne ferons pas marche arrière Marée humaine, hier, à Alger.La rue a mis dans son collimateur une nouvelle cible : le chef d’état-major et vice-ministre de la Défense, Ahmed Gaïd Salah. Pour la première fois depuis le 22 février dernier, les manifestants exigent son départ.","date": "22 Avril 2019", "image": "imgNews1", "categorie": "national"},
                    {"title": "Les étudiants ne lâchent pas prise", "description": "Alger, 14 mai 2019. 10h30. Sous un soleil printanier, le cortège composé de plusieurs dizaines d’étudiants de différentes universités s’ébranle depuis la Fac centrale en direction de la Grande-Poste.", "date": "15 Mai 2019 ", "image": "imgNews1","categorie": "national"},
                    {"title": "Crise vénézuélienne : Juan Guaido a-t-il perdu la partie ?", "description": "Depuis qu’il s’est déclaré président par intérim le 23 janvier, Juan Guaido n’a eu de cesse d’appeler les militaires à rompre les rangs et à tourner le dos au chef de l’Etat socialiste. Il comptait pour cela sur le soutien de dizaines de milliers de personnes, qui descendaient dans la rue à chacun de ses appels à manifester.Mais depuis le soulèvement manqué du 30 avril et l’offensive du pouvoir contre les «traîtres» à l’origine de la tentative de rébellion, le vent semble avoir tourné dans la rue. Samedi, ils n’étaient qu’entre 1500 et 2000 sur la place Alfredo Sadel, dans un quartier de l’est de Caracas majoritairement acquis à l’opposition.","date": "13 Mai 2019", "image": "imgNews1", "categorie": "international"},
                    {"title": "Yémen : Les Houthis se retirent des ports d’Al Hodeïda", "description": "Les rebelles houthis du Yémen ont remis le contrôle de la sécurité des ports d’Al Hodeïda, sur la mer Rouge, à la «garde côtière», mais du travail demeure pour éliminer tout signe de présence militaire, a annoncé hier l’ONU.Le président du Comité de coordination des redéploiements, le général danois Michael Lollesgaard, a salué le transfert de «la sécurité des ports à la garde côtière», selon un communiqué officiel. «Il reste encore beaucoup de travail à faire pour éliminer les signes (de présence militaire), mais la coopération a été très bonne», a-t-il jugé. Si le redéploiement est total, il pourrait donner une impulsion aux efforts de l’ONU pour mettre un terme à la guerre et à la catastrophe humanitaire au Yémen. A signaler que la gestion des revenus des trois ports en question devait être discutée hier à Amman avec leurs représentants et le gouvernement du Yémen, a annoncé lundi l’ONU.","date": "15 Mai 2019", "image": "imgNews1", "categorie": "international"},
                    {"title": "JSMB : Les joueurs réclament leur argent", "description": "Les joueurs de la JSM Béjaïa ont réitéré leurs revendications liées à la régularisation de leur situation financière, puisqu’ils ont interpellé la direction afin d’accélérer les démarches et tenir ses promesses pour le versement de leurs salaires qui tarde à se matérialiser depuis la fin","date": "15 Mai 2019", "image": "imgNews1", "categorie": "Sport"},
                    {"title": "JS Kabylie : Réception en l’honneur des jeunes catégories", "description": "Lundi dans la soirée, l’hôtel Ittourar de Tizi Ouzou a abrité une réception en l’honneur des jeunes catégories de la JS Kabylie et leurs staffs techniques.Les U13 et U12, champions de wilaya de l’année 2018/2019 dans leurs catégories respectives, étaient les premiers à être  reçus et félicités pour leur bon parcours, et ce,  dans une ambiance bon enfant, marquée par la présence de la direction du club kabyle et de nombreux invités. Le président de la JSK, Cherif Mellal, a pris la parole pour féliciter les champions et les vainqueurs du play-off.","date": "22 Avril 2019", "image": "imgNews1", "categorie": "Sport"},
                    {"title": "Ligue 1 : CRB – JSS en nocturne", "description": "La Ligue de football professionnel (LFP) a communiqué sur son site officiel les horaires des rencontres de la 28e journée. Encore une fois, la LFP n’arrive pas à programmer tous les matches à la même heure pour éviter toutes les spéculations sur le résultat final des rencontres.", "date": "15 Mai 2019 ", "image": "imgNews1","categorie": "national"},
                    {"title": "Mouloudia d’Alger : Casoni débarque à Alger", "description": "L’entraîneur du Mouloudia pour la nouvelle saison, le Français Bernard Casoni, et comme annoncé dans ces mêmes colonnes, est depuis hier à Alger où il séjournera durant quatre jours.Bernard Casoni, dont la mission à la tête du club algérois ne débutera officiellement qu’au mois de juin prochain, puisque l’équipe est toujours sous la coupe de Mohamed Mekhazeni pour ce qui reste de la saison en cours, aura néanmoins à régler certains détails inhérents à son récent engagement avec le MCA, avec notamment la paperasse nécessaire pour l’établissement de son permis de travail, mais surtout arrêter avec exactitude le programme de préparation d’intersaison, qui débutera à la mi-juin.","date": "15 Mai 2019", "image": "imgNews1", "categorie": "Sport"}
                   ]"""
                val list: List<News> = gson.fromJson(newsString , Array<News>::class.java).toList()
                return ListNews.newInstance(list)
                /*var gson = Gson()
                val newsString =  """[
                    {"title": "JSMB : Les joueurs réclament leur argent", "description": "Les joueurs de la JSM Béjaïa ont réitéré leurs revendications liées à la régularisation de leur situation financière, puisqu’ils ont interpellé la direction afin d’accélérer les démarches et tenir ses promesses pour le versement de leurs salaires qui tarde à se matérialiser depuis la fin","date": "15 Mai 2019", "image": "imgNews1", "categorie": "Sport"},
                    {"title": "JS Kabylie : Réception en l’honneur des jeunes catégories", "description": "Lundi dans la soirée, l’hôtel Ittourar de Tizi Ouzou a abrité une réception en l’honneur des jeunes catégories de la JS Kabylie et leurs staffs techniques.Les U13 et U12, champions de wilaya de l’année 2018/2019 dans leurs catégories respectives, étaient les premiers à être  reçus et félicités pour leur bon parcours, et ce,  dans une ambiance bon enfant, marquée par la présence de la direction du club kabyle et de nombreux invités. Le président de la JSK, Cherif Mellal, a pris la parole pour féliciter les champions et les vainqueurs du play-off.","date": "22 Avril 2019", "image": "imgNews1", "categorie": "Sport"},
                    {"title": "Ligue 1 : CRB – JSS en nocturne", "description": "La Ligue de football professionnel (LFP) a communiqué sur son site officiel les horaires des rencontres de la 28e journée. Encore une fois, la LFP n’arrive pas à programmer tous les matches à la même heure pour éviter toutes les spéculations sur le résultat final des rencontres.", "date": "15 Mai 2019 ", "image": "imgNews1","categorie": "Sport"},
                    {"title": "Mouloudia d’Alger : Casoni débarque à Alger", "description": "L’entraîneur du Mouloudia pour la nouvelle saison, le Français Bernard Casoni, et comme annoncé dans ces mêmes colonnes, est depuis hier à Alger où il séjournera durant quatre jours.Bernard Casoni, dont la mission à la tête du club algérois ne débutera officiellement qu’au mois de juin prochain, puisque l’équipe est toujours sous la coupe de Mohamed Mekhazeni pour ce qui reste de la saison en cours, aura néanmoins à régler certains détails inhérents à son récent engagement avec le MCA, avec notamment la paperasse nécessaire pour l’établissement de son permis de travail, mais surtout arrêter avec exactitude le programme de préparation d’intersaison, qui débutera à la mi-juin.","date": "15 Mai 2019", "image": "imgNews1", "categorie": "Sport"}]"""
                val list: List<News> = gson.fromJson(newsString , Array<News>::class.java).toList()
                return ListNews.newInstance(list)*/
            }
            2 -> {
                var gson = Gson()
                val newsString =  """[{"title": "Nous ne ferons pas marche arrière", "description": "Des centaines de milliers de manifestants dans les rues d’Alger Nous ne ferons pas marche arrière Marée humaine, hier, à Alger.La rue a mis dans son collimateur une nouvelle cible : le chef d’état-major et vice-ministre de la Défense, Ahmed Gaïd Salah. Pour la première fois depuis le 22 février dernier, les manifestants exigent son départ.","date": "22 Avril 2019", "image": "imgNews1", "categorie": "national"},
                    {"title": "Nous ne ferons pas marche arrière", "description": "Des centaines de milliers de manifestants dans les rues d’Alger Nous ne ferons pas marche arrière Marée humaine, hier, à Alger.La rue a mis dans son collimateur une nouvelle cible : le chef d’état-major et vice-ministre de la Défense, Ahmed Gaïd Salah. Pour la première fois depuis le 22 février dernier, les manifestants exigent son départ.","date": "22 Avril 2019", "image": "imgNews1", "categorie": "national"},
                    {"title": "Les étudiants ne lâchent pas prise", "Alger, 14 mai 2019. 10h30. Sous un soleil printanier, le cortège composé de plusieurs dizaines d’étudiants de différentes universités s’ébranle depuis la Fac centrale en direction de la Grande-Poste.", "date": "15 Mai 2019 ", "image": "imgNews1","categorie": "national"}]"""
                val list: List<News> = gson.fromJson(newsString , Array<News>::class.java).toList()
                return ListNews.newInstance(list)
            }
            3 -> {
                var gson = Gson()
                val newsString =  """[
                    {"title": "Drama algéro-tunisienne Machiir de Muhammet Gok : Quête et enquête du bonheur", "description": "Le feuilleton Machaiir (Sentiments), diffusé sur Carthage + et Ennahar TV, est l’évidence de l’édification du Maghreb à travers la culture. La preuve, c’est une production mixte de deux pays voisins.Donc, placé sous le signe de l’amitié et la fraternité algéro-tunisienne. Ce feuilleton a été tourné en Tunisie. Un casting pluriel comptant Hassan Kechach, qui n’est plus à présenter (Ben Boulaïd, Lotfi, Les Sept remparts d’Ahmed Rachedi, En attendant les hirondelles de Karim Moussaoui…), l’actrice tunisienne, Meriem Benchaâbane, Sara Lalama, Nabil Asli, Adel Cheikh, Ahmed El Andaloussi, Rym Benmasoûd, Mohamed Mourad, Kenza Chiha ainsi que des guest-stars, comme Mohaled Karii, Dalila Meftah, Khaled Houissa, Ali El Hindi, Abdelghani Bentara, Tewfik El Ayab… Machaiir (Sentiments) est signé par Muhammet Gok. Un réalisateur turc établi en Allemagne.","date": "7 Mai 2019", "image": "imgNews1", "categorie": "Culture"},
                   {"title": "Festival européen d’Algérie. Concert du Arcis Saxophon Quartett : Quatre musiciens dans le vent", "description": "Cette année, le Festival européen d’Algérie, un événement musical incontournable qui, encore une fois, veut incarner et présenter un rendez-vous annuel offrant une opportunité d’échange, de promotion du dialogue culturel entre l’Algérie et l’UE et aussi une tribune de choix et une expression directe de la pluralité et de la diversité culturelle européenne.L’hôte de la soirée de lundi soir était l’Allemagne. Et ceux qui ont défendu ses couleurs, ce sont les musiciens du Arcis Saxophon Quartett. Ce sont quatre instrumentistes.","date": "28 Avril 2019", "image": "imgNews1", "categorie": "Culture"},
                   {"title": "Contribution : Un joyau nommé Tassili N’Ajjer", "description": "C’est le Mois du patrimoine et nous ne sommes pas en panne de sujets, tant celui de notre pays, qu’il soit naturel ou culturel, est riche et diversifié.Qu’il soit immatériel ou matériel, il nous est venu du passé, il fait partie intégrante de notre vie quotidienne, et il est de notre devoir de le faire vivre et de le transmettre. Un proverbe africain ne dit-il pas : «La culture est la possibilité même de créer, de renouveler et de partager des valeurs, le souffle qui accroît la vitalité de l’humanité.»","date": "20 Avril 2019", "image": "imgNews1", "categorie": "Culture"}
                   ]"""
                val list: List<News> = gson.fromJson(newsString , Array<News>::class.java).toList()
                return ListNews.newInstance(list)

            }
            4 -> {
                var gson = Gson()
                val newsString =  """[
                    {"title": "Crise vénézuélienne : Juan Guaido a-t-il perdu la partie ?", "description": "Depuis qu’il s’est déclaré président par intérim le 23 janvier, Juan Guaido n’a eu de cesse d’appeler les militaires à rompre les rangs et à tourner le dos au chef de l’Etat socialiste. Il comptait pour cela sur le soutien de dizaines de milliers de personnes, qui descendaient dans la rue à chacun de ses appels à manifester.Mais depuis le soulèvement manqué du 30 avril et l’offensive du pouvoir contre les «traîtres» à l’origine de la tentative de rébellion, le vent semble avoir tourné dans la rue. Samedi, ils n’étaient qu’entre 1500 et 2000 sur la place Alfredo Sadel, dans un quartier de l’est de Caracas majoritairement acquis à l’opposition.","date": "13 Mai 2019", "image": "imgNews1", "categorie": "international"},
                   {"title": "Yémen : Les Houthis se retirent des ports d’Al Hodeïda", "description": "Les rebelles houthis du Yémen ont remis le contrôle de la sécurité des ports d’Al Hodeïda, sur la mer Rouge, à la «garde côtière», mais du travail demeure pour éliminer tout signe de présence militaire, a annoncé hier l’ONU.Le président du Comité de coordination des redéploiements, le général danois Michael Lollesgaard, a salué le transfert de «la sécurité des ports à la garde côtière», selon un communiqué officiel. «Il reste encore beaucoup de travail à faire pour éliminer les signes (de présence militaire), mais la coopération a été très bonne», a-t-il jugé. Si le redéploiement est total, il pourrait donner une impulsion aux efforts de l’ONU pour mettre un terme à la guerre et à la catastrophe humanitaire au Yémen. A signaler que la gestion des revenus des trois ports en question devait être discutée hier à Amman avec leurs représentants et le gouvernement du Yémen, a annoncé lundi l’ONU.","date": "15 Mai 2019", "image": "imgNews1", "categorie": "international"},
                   {"title": "Territoires palestiniens occupés : Le blocus allégé à Ghaza", "description": "Dans le cadre de l’allégement du blocus qui étouffe la bande de Ghaza et ses deux millions d’habitants, l’occupation israélienne a élargi la zone de pêche en face des côtes ghazaouies à 12 milles marins.Après neuf jours de fermeture, Israël a rouvert, hier matin, les points de passage de Beit Hanoune, Erez, pour les personnes et celui de Karm Abou Salem par lequel entrent à Ghaza les marchandises diverses, dont le carburant et les matériaux de construction qui ont une valeur stratégique. Cette ouverture, annoncée officiellement par une porte-parole du ministère israélien de la Défense, vient dans le cadre de l’allégement du blocus que l’occupation impose à l’enclave palestinienne depuis une douzaine d’années.","date": "13 Mai 2019", "image": "imgNews1", "categorie": "international"},]"""
                val list: List<News> = gson.fromJson(newsString , Array<News>::class.java).toList()
                return ListNews.newInstance(list)
            }
            else -> {
                var gson = Gson()
                val newsString =  """[
                    {"title": "Crise vénézuélienne : Juan Guaido a-t-il perdu la partie ?", "description": "Depuis qu’il s’est déclaré président par intérim le 23 janvier, Juan Guaido n’a eu de cesse d’appeler les militaires à rompre les rangs et à tourner le dos au chef de l’Etat socialiste. Il comptait pour cela sur le soutien de dizaines de milliers de personnes, qui descendaient dans la rue à chacun de ses appels à manifester.Mais depuis le soulèvement manqué du 30 avril et l’offensive du pouvoir contre les «traîtres» à l’origine de la tentative de rébellion, le vent semble avoir tourné dans la rue. Samedi, ils n’étaient qu’entre 1500 et 2000 sur la place Alfredo Sadel, dans un quartier de l’est de Caracas majoritairement acquis à l’opposition.","date": "13 Mai 2019", "image": "imgNews1", "categorie": "international"},
                   {"title": "Yémen : Les Houthis se retirent des ports d’Al Hodeïda", "description": "Les rebelles houthis du Yémen ont remis le contrôle de la sécurité des ports d’Al Hodeïda, sur la mer Rouge, à la «garde côtière», mais du travail demeure pour éliminer tout signe de présence militaire, a annoncé hier l’ONU.Le président du Comité de coordination des redéploiements, le général danois Michael Lollesgaard, a salué le transfert de «la sécurité des ports à la garde côtière», selon un communiqué officiel. «Il reste encore beaucoup de travail à faire pour éliminer les signes (de présence militaire), mais la coopération a été très bonne», a-t-il jugé. Si le redéploiement est total, il pourrait donner une impulsion aux efforts de l’ONU pour mettre un terme à la guerre et à la catastrophe humanitaire au Yémen. A signaler que la gestion des revenus des trois ports en question devait être discutée hier à Amman avec leurs représentants et le gouvernement du Yémen, a annoncé lundi l’ONU.","date": "15 Mai 2019", "image": "imgNews1", "categorie": "international"},
                   {"title": "Territoires palestiniens occupés : Le blocus allégé à Ghaza", "description": "Dans le cadre de l’allégement du blocus qui étouffe la bande de Ghaza et ses deux millions d’habitants, l’occupation israélienne a élargi la zone de pêche en face des côtes ghazaouies à 12 milles marins.Après neuf jours de fermeture, Israël a rouvert, hier matin, les points de passage de Beit Hanoune, Erez, pour les personnes et celui de Karm Abou Salem par lequel entrent à Ghaza les marchandises diverses, dont le carburant et les matériaux de construction qui ont une valeur stratégique. Cette ouverture, annoncée officiellement par une porte-parole du ministère israélien de la Défense, vient dans le cadre de l’allégement du blocus que l’occupation impose à l’enclave palestinienne depuis une douzaine d’années.","date": "13 Mai 2019", "image": "imgNews1", "categorie": "international"},]"""
                val list: List<News> = gson.fromJson(newsString , Array<News>::class.java).toList()
                return ListNews.newInstance(list)
            }
        }
    }

    // this counts total number of tabs
    override fun getCount(): Int {
        return totalTabs
    }
}